
#GET all planets
GET http://localhost:8000/v1/planets HTTP/1.1
###

#GET all launches
GET http://localhost:8000/v1/launches HTTP/1.1
###

#POST add new launch
POST http://localhost:8000/v1/launches HTTP/1.1
content-type: application/json

{
    "mission": "KAI1234",
    "rocket": "KAI Experimental IS1",
    "target": "Kepler-442 b",
    "launchDate": "January 17, 2030"
}
###

#DELETE launch by ID
DELETE http://localhost:8000/v1/launches/118 HTTP/1.1
###

#SpaceX REST API
POST https://api.spacexdata.com/v4/launches/query HTTP/1.1
content-type: application/json

{
    "query": {},
    "options": {
        "pagination": false,
        "populate": [
            {
                "path": "rocket",
                "select": {
                    "name": 1
                }
            },
            {
                "path": "payloads",
                "select": {
                    "customers": 1
                }
            }
        ]
    }
  }